# Generated by Django 5.2.7 on 2026-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
